version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - client
    restart: always # This service should always be running
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server # context field is to mention where to look for the dockerfile.
    volumes:
      - /app/node_modules # don't update the contents of this directory
      - ./server:/app # Map ./server content to /app content
    environment:
      - REDIS_HOST=redis # hostname will be the name of service
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres # name of the service. Remaining values are taken from the Docker Hub documentation
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
